hps: include array for std::array.
Explicitly include array for std::array. Otherwise it may cause
error: implicit instantiation of undefined template
'std::array<std::unique_ptr<hps::Filter>, 2>'
when libchrome is no longer implicitly including array.

BUG=b:190446478
TEST=emerge hpsd with newer libchrome draft

Change-Id: I11a70b93ccc503e74c4171a0f1a8fa83f4dd1082
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3205149
Tested-by: Qijiang Fan <fqj@google.com>
Reviewed-by: Grace Cham <hscham@chromium.org>
Reviewed-by: Evan Benn <evanbenn@chromium.org>
Reviewed-by: Stuart Langley <slangley@chromium.org>
Commit-Queue: Evan Benn <evanbenn@chromium.org>