Revert "cryptohome: refactor AuthSession::AuthenticateAuthFactor."
This reverts commit a182349a307255f9dee7d70251f22288a0c405e5.

Reason for revert: Breaking the build
../../../../../../../tmp/portage/chromeos-base/cryptohome-0.0.2-r4873/work/cryptohome-0.0.2/platform2/cryptohome/auth_session_tpm_simulator_unittest.cc:94:68: error: too few arguments to function call, expected 3, have 2
  auth_session.AuthenticateAuthFactor(request, future.GetCallback());
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              ^
../../../../../../../tmp/portage/chromeos-base/cryptohome-0.0.2-r4873/work/cryptohome-0.0.2/platform2/cryptohome/auth_session.h:167:8: note: 'AuthenticateAuthFactor' declared here
  void AuthenticateAuthFactor(base::span<const std::string> auth_factor_labels,
       ^
1 error generated.

[98/349] CXX obj/cryp

Original change's description:
> cryptohome: refactor AuthSession::AuthenticateAuthFactor.
>
> Following the proto change in AuthentiacateAuthFactorRequest,
> AuthenticateAuthFactor now allow either |auth_factor_label|
> or |auth_factor_labels| specified but not both.
>
> General speaking, the auth flow works as follows:
> 1. Derive the auth label arity from the auth factor type.
> 2. For auth factors that do not allow a label, construct a verifier
> and verify as authentication. Currently only LegacyFingerprint
> works this way.
> 2. (Most common) Exact 1 auth factor label is needed to find exactly
> one auth factor. Authenticate with the single auth factor, while a
> verifier is optionally used if the auth request signals it.
> 3. (Only for signin fingerprint) more than 1 auth factor labels are
> allowed. To be implemented: Carry out extra logic to locate the
> single auth factor then proceed as step 2.
>
> Extract code logic in step 2 as a helper function so we can reuse it later.
>
> BUG=b:263204156
> TEST=FEATURES=test emerge-$B cryptohome
>
> Change-Id: I9fb4119c7d0e0b470c673b6f168cc13b83032956
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4117788
> Tested-by: Zi Lin <lziest@google.com>
> Reviewed-by: Betul Soysal <betuls@google.com>
> Reviewed-by: John Admanski <jadmanski@chromium.org>
> Commit-Queue: Zi Lin <lziest@google.com>

Bug: b:263204156
Change-Id: I4a6d358e0f7f74bafa8bfdc682183aec51b0c31f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4204047
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Owners-Override: Raul Rangel <rrangel@chromium.org>