vm_tools: concierge: missing sequence_checker_ check conversion
https://crrev.com/c/4535481 missed to convert the checker and emerging
the concierge fails.

```
vm_host_tools-9999: ../../../../../../../../../mnt/host/source/src/platform2/vm_tools/concierge/arc_vm.cc:926:10: error: use of undeclared identifier 'sequence_checker_'
vm_host_tools-9999:   DCHECK(sequence_checker_.CalledOnValidSequence());
vm_host_tools-9999:          ^
```

BUG=none
TEST=emerge-$BOARD vm_host_tools

Change-Id: Ib4168bf3f7d8792f3dfd65ee8854c9fdf18e80e6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4540862
Commit-Queue: Junichi Uekawa <uekawa@chromium.org>
Tested-by: Shin Kawamura <kawasin@google.com>
Reviewed-by: Keiichi Watanabe <keiichiw@chromium.org>
Reviewed-by: Junichi Uekawa <uekawa@chromium.org>