sepolicy: Allow read proc_filesystems on install
It looks like `mount` sometimes tries to read `/proc/filesystems` while
installing, which is currently not allowed:
```
avc:  denied  { read } for
  pid=6293 comm="mount"
  name="filesystems" dev="proc" ino=4026532080
  scontext=u:r:cros_chromeos_install:s0
  tcontext=u:object_r:proc_filesystems:s0
  tclass=file
  permissive=0
```
resulting in:
```
src/util.rs:118 INFO: >>> mount: /tmp/install-mount-point: mount failed: Operation not permitted.
src/util.rs:118 INFO: >>> umount: /tmp/install-mount-point: not mounted.
src/bin/os_install_service/install.rs:169 ERROR: installation failed: <...>
```

This prevents certain devices from installing ChromeOS Flex.

Allow cros_chromeos_install to read proc_filesystems, so that these
devices can install.

BUG=b:241771611
TEST=`FEATURES=test emerge-octopus selinux-policy`
TEST=`FEATURES=test emerge-reven selinux-policy`

Change-Id: I21b9cb7efc8008e8a92720635b1abe52fa168463
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3838736
Reviewed-by: Betul Soysal <betuls@google.com>
Tested-by: Ted Brandston <tbrandston@google.com>
Commit-Queue: Betul Soysal <betuls@google.com>
Auto-Submit: Ted Brandston <tbrandston@google.com>