faced: Add internal locking to FakeCameraService
We have been seeing some flakes of the camera tests in CQ (b/255460130),
where the camera tests fail with a bad pointer dereference:

    [ RUN      ] CameraClientTest.CaptureFrames
    camera_unittests: [camera_client.cc(157)] Starting capture: device = 0, fourcc = NV12, width = 1920, height = 1080, fps = 30
    camera_unittests: [camera_client.cc(224)] Stopping capture on camera: 0
    Error: /var/cache/portage/chromeos-base/faced/out/Default/camera_unittests: failed with signal SIGSEGV(11)

Though I haven't been able to reproduce the same bug as in CQ, I have
been able to trigger TSAN failures by stress testing the camera unit
tests (in particular, running large numbers of the test in parallel
repeatedly).

This CL adds locks to the FakeCameraService class to avoid racey
accesses on its internal members. After this CL, stress testing the
`camera_unittests` binary no longer produces TSAN warnings.

BUG=b:255460130
TEST=Described above.

Change-Id: Iaef41f6e4d80be8e5470486a5285dd2427503ab8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4037368
Reviewed-by: Ben Kersten <bkersten@google.com>
Commit-Queue: David Greenaway <dgreenaway@google.com>
Tested-by: David Greenaway <dgreenaway@google.com>