vm_tools: crostini_client: make error messages less cryptic
End users are not interested in exact arguments that have been passed
into a function, or file and line number where said function is defined,
but rather in the cause of the error. Let's rework error reporting to
trim noise. Compare:

	Error: routine at frontends/vmc.rs:250 `vm_start(vm_name,&user_id_hash,features,user_disks,!matches.opt_present("no-start-lxd"))` failed: insufficient disk space to start VM

vs

	Error: operation `vm_start` failed: insufficient disk space to start VM

BUG=b:178895203
TEST=Try using vmc with disk full, or without network, etc.

Change-Id: Ia33cae0006d45f620a52a06aa223cd7ac73eee90
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2674426
Reviewed-by: Stephen Barber <smbarber@chromium.org>
Reviewed-by: Nicholas Verne <nverne@chromium.org>
Tested-by: Dmitry Torokhov <dtor@chromium.org>
Commit-Queue: Dmitry Torokhov <dtor@chromium.org>