cryptohome: Add code to cryptohome utility to check namespace
Add code to the cryptohome command line utility, to mount_guest_ex
command to check whether the namespace has been created at
/run/namespaces/mnt_chrome.
cryptohomed has an indirect synchronization with session_manager
through D-Bus when the 'mount Guest session' request comes from Chrome
(Login screen). But cryptohome command line utility doesn't have any
synchronization with session_manager. And the namespace creation will
be moved to session_manager. So, in case of a failure in
cryptohome.GuestSession which uses cryptohome utility we need to know
whether the reason of the failure is a race condition in the namespace
creation or not.

BUG=chromium:1132444
TEST=Boot to OOBE or login screen and delete the file at
/run/namespaces/mnt_chrome. Then 'cryptohome --action=mount_guest_ex'
should print the following error message:
[ERROR:mount_utils.cc(32)] statfs(/run/namespaces/mnt_chrome) failed: No such file or directory (2)
User session mount namespace at /run/namespaces/mnt_chrome has not been created yet.
error: CRYPTOHOME_ERROR_MOUNT_FATAL
Mount failed.

Change-Id: I33b3c8eb0d78713a83b0f5f9ce75b443db05a108
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2596385
Tested-by: Betul Soysal <betuls@google.com>
Commit-Queue: Betul Soysal <betuls@google.com>
Reviewed-by: Jorge Lucangeli Obes <jorgelo@chromium.org>
Reviewed-by: Leo Lai <cylai@google.com>