vm_tools: rename UTF-8 data to placate cros format
The UTF8_test.txt file intentionally contains invalid UTF-8 sequences,
and `cros format` attempts to reformat .txt files, so it explodes:

  ERROR: vm_tools/syslog/UTF8_test.txt: file is not UTF-8 compatible

It seems like the simplest way to "fix" this is to just rename the file
so `cros format` doesn't try to reformat it.

BUG=b:187785601
TEST=cros format vm_tools/

Change-Id: I398a94ada3d2df218511d66b23ece3d5221048ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4977784
Commit-Queue: Daniel Verkamp <dverkamp@chromium.org>
Tested-by: Daniel Verkamp <dverkamp@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>