cryptohome: fix glibc 2.34 build breakage
Starting with glibc 2.34, sys/mount.h exposes the kernel
value MS_NOSYMFOLLOW = 256 which is in accordance with
the value defined by platform.h.

The include guard in platform.h is correct but we need to
also include mount.h which defines the value in glibc,
otherwise MS_NOSYMFOLLOW will be redefined conflicting
with mount.h when it will eventually be included.

Example failure:
In file included from .../cryptohome-9999/platform2/cryptohome/storage/mount.cc:10:
/build/eve/usr/include/sys/mount.h:51:3: error: expected identifier
  MS_NOSYMFOLLOW = 256,         /* Do not follow symlinks.  */
  ^
.../cryptohome-9999/platform2/cryptohome/platform.h:38:24: note: expanded from macro 'MS_NOSYMFOLLOW'

BUG=b:235960683
TEST=Local builds against glibc 2.34.

Change-Id: I5acdb15ea866f32e4aaec0035629b40483f2ee70
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3714386
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Sarthak Kukreti <sarthakkukreti@chromium.org>