cryptohome: Fix missing include in /crypto/
Fix the following build error that's observed in some configurations:

  secure_blob_util.cc:39:37: error: no member named 'checked_cast' in
  namespace 'base'

BUG=b:216638252
TEST=none

Change-Id: Ia2544e2e0419c17853319b381e2e6b9c74e1197a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3420413
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Tested-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Greg Kerr <kerrnel@chromium.org>
Commit-Queue: Greg Kerr <kerrnel@chromium.org>
Tested-by: Greg Kerr <kerrnel@chromium.org>