diagnostics: remove unused variable
`err` here is unused, and Clang will soon complain about this by
default:

```
diagnostics-0.0.1-r2239:
[...]/psr_cmd.cc:67:7:
error: variable 'err' set but not used
[-Werror,-Wunused-but-set-variable]
diagnostics-0.0.1-r2239:   int err;
```

BUG=b:296450693
TEST=emerge-amd64-generic diagnostics

Change-Id: Ida4c387a12f8c448ac8df46fc2f151ba58567427
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4846421
Commit-Queue: George Burgess <gbiv@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Kerker Yang <kerker@chromium.org>
Tested-by: Kerker Yang <kerker@chromium.org>