common-mk: Remove `throw_on_failure` flag override from TestRunner
Currently, for all test binaries using the common-mk TestRunner
implementation, any and all GoogleTest EXPECT or ASSERT failures result
in the message:

    libc++abi: terminating due to uncaught exception of type testing::internal::GoogleTestFailureException: ...
    Error: /foo/bar/my_test_binary: failed with signal SIGIOT|SIGABRT(6)

followed by the test binary immediately aborting.

The reason for the abort is that the TestRunner overrides the GoogleTest
`throw_on_failure` flag, forcing the flag to `true`. In contrast, when
the flag is in its default `false` state, GoogleTest will continue
running other tests, making it possible to see multiple failures in one
run.

It is not clear why this flag override was originally introduced: it was
included in the initial commit of a test runner for the `mist` package
in https://crrev.com/c/56718 back in 2013 without further comment. The
`mist` test runner became the common-mk test runner in
https://crrev.com/c/508239. Finally, the flag override was moved to the
TestRunner class in https://crrev.com/c/1838496.

Remove the flag override, restoring the default GoogleTest behaviour of
continuing after expectation failures. Users can still manually add the
flag on the command line if desired.

Tested by deliberately adding EXPECT failures to a test suite using the
common test runner, and ensuring that the test suite still runs to
completion.

BUG=b:269383407
TEST=Described above

Change-Id: Ib6c8db2dbae727592468f370d113382cc1f81302
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4235600
Tested-by: Tom Hughes <tomhughes@chromium.org>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Auto-Submit: David Greenaway <dgreenaway@google.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>