libhwsec-foundation: Support more optional fields
The following types of fields have explicit presence in proto3:
- Embedded message fields.
- Fields marked with optional or required.
- Fileds in the oneof scope.

A slightly different set of rules apply in proto2, but the key point
here is that it's difficult to judge the presence info with the proto
field declaration (for example, we can't know whether an embedded proto
field is a message or an enum, but they have different presence). Use
constraint to check the has_name field conditionally to handle all
cases.

Below is the difference of a start auth session reply of a user with a
password and a PIN factor.

Old format
[user_data_auth.StartAuthSessionReply] {
  error: CRYPTOHOME_ERROR_NOT_SET
  error_info: [user_data_auth.CryptohomeErrorInfo] {
    error_id:
    readable_error_id:
    primary_action: PRIMARY_NO_ERROR
    possible_actions: {}
  }
  auth_session_id: 3BC60948ED65122F3362A1F7964FA60C
  broadcast_id: BAF1FFBF6205D6C48C79BDCA17645CE1
  user_exists: true
  auth_factors: {
    [user_data_auth.AuthFactor] {
      type: AUTH_FACTOR_TYPE_PASSWORD
      label: password
      common_metadata: [user_data_auth.CommonMetadata] {
        chromeos_version_last_updated: 15718.0.0
        chrome_version_last_updated:
        lockout_policy: LOCKOUT_POLICY_NONE
        user_specified_name:
      }
      password_metadata: [user_data_auth.PasswordMetadata] {
        hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
          algorithm: HASH_TYPE_UNSPECIFIED
          salt:
        }
      }
      pin_metadata: [user_data_auth.PinMetadata] {
        auth_locked: false
        hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
          algorithm: HASH_TYPE_UNSPECIFIED
          salt:
        }
      }
      cryptohome_recovery_metadata: [user_data_auth...Metadata] {
        mediator_pub_key:
      }
      kiosk_metadata: [user_data_auth.KioskMetadata] {
      }
      smart_card_metadata: [user_data_auth.SmartCardMetadata] {
        public_key_spki_der:
      }
      legacy_fingerprint_metadata: [user_data_auth...Metadata] {
      }
      fingerprint_metadata: [user_data_auth.FingerprintMetadata] {
      }
    },
    [user_data_auth.AuthFactor] {
      type: AUTH_FACTOR_TYPE_PIN
      label: pin
      common_metadata: [user_data_auth.CommonMetadata] {
        chromeos_version_last_updated: 15718.0.0
        chrome_version_last_updated:
        lockout_policy: LOCKOUT_POLICY_ATTEMPT_LIMITED
        user_specified_name:
      }
      password_metadata: [user_data_auth.PasswordMetadata] {
        hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
          algorithm: HASH_TYPE_UNSPECIFIED
          salt:
        }
      }
      pin_metadata: [user_data_auth.PinMetadata] {
        auth_locked: false
        hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
          algorithm: HASH_TYPE_UNSPECIFIED
          salt:
        }
      }
      cryptohome_recovery_metadata: [user_data_auth...Metadata] {
        mediator_pub_key:
      }
      kiosk_metadata: [user_data_auth.KioskMetadata] {
      }
      smart_card_metadata: [user_data_auth.SmartCardMetadata] {
        public_key_spki_der:
      }
      legacy_fingerprint_metadata: [user_data_auth...Metadata] {
      }
      fingerprint_metadata: [user_data_auth.FingerprintMetadata] {
      }
    }
  }
  configured_auth_factors_with_status: {
    [user_data_auth.AuthFactorWithStatus] {
      auth_factor: [user_data_auth.AuthFactor] {
        type: AUTH_FACTOR_TYPE_PASSWORD
        label: password
        common_metadata: [user_data_auth.CommonMetadata] {
          chromeos_version_last_updated: 15718.0.0
          chrome_version_last_updated:
          lockout_policy: LOCKOUT_POLICY_NONE
          user_specified_name:
        }
        password_metadata: [user_data_auth.PasswordMetadata] {
          hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
            algorithm: HASH_TYPE_UNSPECIFIED
            salt:
          }
        }
        pin_metadata: [user_data_auth.PinMetadata] {
          auth_locked: false
          hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
            algorithm: HASH_TYPE_UNSPECIFIED
            salt:
          }
        }
        cryptohome_recovery_metadata: [user_data_auth...Metadata] {
          mediator_pub_key:
        }
        kiosk_metadata: [user_data_auth.KioskMetadata] {
        }
        smart_card_metadata: [user_data_auth.SmartCardMetadata] {
          public_key_spki_der:
        }
        legacy_fingerprint_metadata: [user_data_auth...Metadata] {
        }
        fingerprint_metadata: [user_data_auth.FingerprintMetadata] {
        }
      }
      available_for_intents: {
        AUTH_INTENT_DECRYPT,
        AUTH_INTENT_VERIFY_ONLY,
        AUTH_INTENT_WEBAUTHN
      }
      status_info: [user_data_auth.StatusInfo] {
        time_available_in: 0 (0x0000000000000000)
      }
    },
    [user_data_auth.AuthFactorWithStatus] {
      auth_factor: [user_data_auth.AuthFactor] {
        type: AUTH_FACTOR_TYPE_PIN
        label: pin
        common_metadata: [user_data_auth.CommonMetadata] {
          chromeos_version_last_updated: 15718.0.0
          chrome_version_last_updated:
          lockout_policy: LOCKOUT_POLICY_ATTEMPT_LIMITED
          user_specified_name:
        }
        password_metadata: [user_data_auth.PasswordMetadata] {
          hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
            algorithm: HASH_TYPE_UNSPECIFIED
            salt:
          }
        }
        pin_metadata: [user_data_auth.PinMetadata] {
          auth_locked: false
          hash_info: [user_data_auth.KnowledgeFactorHashInfo] {
            algorithm: HASH_TYPE_UNSPECIFIED
            salt:
          }
        }
        cryptohome_recovery_metadata: [user_data_auth...Metadata] {
          mediator_pub_key:
        }
        kiosk_metadata: [user_data_auth.KioskMetadata] {
        }
        smart_card_metadata: [user_data_auth...Metadata] {
          public_key_spki_der:
        }
        legacy_fingerprint_metadata: [yda.LegacyFingerprintMetadata] {
        }
        fingerprint_metadata: [user_data_auth.FingerprintMetadata] {
        }
      }
      available_for_intents: {
        AUTH_INTENT_DECRYPT,
        AUTH_INTENT_VERIFY_ONLY,
        AUTH_INTENT_WEBAUTHN
      }
      status_info: [user_data_auth.StatusInfo] {
        time_available_in: 0 (0x0000000000000000)
      }
    }
  }
}

New format
[user_data_auth.StartAuthSessionReply] {
  error: CRYPTOHOME_ERROR_NOT_SET
  auth_session_id: B5F041EC34C632DD22869BBC32A24A35
  broadcast_id: 1B9EA0ECB010BA8170C72846C83324AD
  user_exists: true
  auth_factors: {
    [user_data_auth.AuthFactor] {
      type: AUTH_FACTOR_TYPE_PASSWORD
      label: password
      common_metadata: [user_data_auth.CommonMetadata] {
        chromeos_version_last_updated: 15718.0.0
        chrome_version_last_updated:
        lockout_policy: LOCKOUT_POLICY_NONE
        user_specified_name:
      }
      password_metadata: [user_data_auth.PasswordMetadata] {
      }
    },
    [user_data_auth.AuthFactor] {
      type: AUTH_FACTOR_TYPE_PIN
      label: pin
      common_metadata: [user_data_auth.CommonMetadata] {
        chromeos_version_last_updated: 15718.0.0
        chrome_version_last_updated:
        lockout_policy: LOCKOUT_POLICY_ATTEMPT_LIMITED
        user_specified_name:
      }
      pin_metadata: [user_data_auth.PinMetadata] {
        auth_locked: false
      }
    }
  }
  configured_auth_factors_with_status: {
    [user_data_auth.AuthFactorWithStatus] {
      auth_factor: [user_data_auth.AuthFactor] {
        type: AUTH_FACTOR_TYPE_PASSWORD
        label: password
        common_metadata: [user_data_auth.CommonMetadata] {
          chromeos_version_last_updated: 15718.0.0
          chrome_version_last_updated:
          lockout_policy: LOCKOUT_POLICY_NONE
          user_specified_name:
        }
        password_metadata: [user_data_auth.PasswordMetadata] {
        }
      }
      available_for_intents: {
        AUTH_INTENT_DECRYPT,
        AUTH_INTENT_VERIFY_ONLY,
        AUTH_INTENT_WEBAUTHN
      }
    },
    [user_data_auth.AuthFactorWithStatus] {
      auth_factor: [user_data_auth.AuthFactor] {
        type: AUTH_FACTOR_TYPE_PIN
        label: pin
        common_metadata: [user_data_auth.CommonMetadata] {
          chromeos_version_last_updated: 15718.0.0
          chrome_version_last_updated:
          lockout_policy: LOCKOUT_POLICY_ATTEMPT_LIMITED
          user_specified_name:
        }
        pin_metadata: [user_data_auth.PinMetadata] {
          auth_locked: false
        }
      }
      available_for_intents: {
        AUTH_INTENT_DECRYPT,
        AUTH_INTENT_VERIFY_ONLY,
        AUTH_INTENT_WEBAUTHN
      }
      status_info: [user_data_auth.StatusInfo] {
        time_available_in: 0 (0x0000000000000000)
      }
    }
  }
}

BUG=b:220231404
TEST=check output of cryptohome CLI

Change-Id: I234bac188c8e28337dd2eead73800487ee94e944
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5153662
Reviewed-by: Yi Chou <yich@google.com>
Commit-Queue: Howard Yang <hcyang@google.com>
Tested-by: Howard Yang <hcyang@google.com>